ITEM_MAP = {
    "Item_Ammo_12Guage_C": "12 Gauge Ammo",
    "Item_Ammo_300Magnum_C": "300 Magnum Ammo",
    "Item_Ammo_45ACP_C": ".45 ACP Ammo",
    "Item_Ammo_556mm_C": "5.56mm Ammo",
    "Item_Ammo_762mm_C": "7.62mm Ammo",
    "Item_Ammo_9mm_C": "9mm Ammo",
    "Item_Ammo_Bolt_C": "Crossbow Bolt",
    "Item_Ammo_Flare_C": "Flare Gun Ammo",
    "Item_Armor_C_01_Lv3_C": "Military Vest (Level 3)",
    "Item_Armor_D_01_Lv2_C": "Police Vest (Level 2)",
    "Item_Armor_E_01_Lv1_C": "Police Vest (Level 1)",
    "Item_Attach_Weapon_Lower_AngledForeGrip_C": "Angled Foregrip",
    "Item_Attach_Weapon_Lower_Foregrip_C": "Vertical Foregrip",
    "Item_Attach_Weapon_Lower_HalfGrip_C": "Half Grip",
    "Item_Attach_Weapon_Lower_LaserPointer_C": "Laser Sight",
    "Item_Attach_Weapon_Lower_LightweightForeGrip_C": "Light Grip",
    "Item_Attach_Weapon_Lower_QuickDraw_Large_Crossbow_C":
        "QuickDraw Crossbow Quiver",
    "Item_Attach_Weapon_Lower_ThumbGrip_C": "Thumb Grip",
    "Item_Attach_Weapon_Magazine_Extended_Large_C": "Large Extended Mag",
    "Item_Attach_Weapon_Magazine_Extended_Medium_C": "Medium Extended Mag",
    "Item_Attach_Weapon_Magazine_Extended_Small_C": "Small Extended Mag",
    "Item_Attach_Weapon_Magazine_Extended_SniperRifle_C":
        "Sniper Rifle Extended Mag",
    "Item_Attach_Weapon_Magazine_ExtendedQuickDraw_Large_C":
        "Large Extended QuickDraw Mag",
    "Item_Attach_Weapon_Magazine_ExtendedQuickDraw_Medium_C":
        "Medium Extended QuickDraw Mag",
    "Item_Attach_Weapon_Magazine_ExtendedQuickDraw_Small_C":
        "Small Extended QuickDraw Mag",
    "Item_Attach_Weapon_Magazine_ExtendedQuickDraw_SniperRifle_C":
        "Sniper Rifle Extended QuickDraw Mag",
    "Item_Attach_Weapon_Magazine_QuickDraw_Large_C": "Large QuickDraw Mag",
    "Item_Attach_Weapon_Magazine_QuickDraw_Medium_C": "Medium Quickdraw Mag",
    "Item_Attach_Weapon_Magazine_QuickDraw_Small_C": "Small Quickdraw Mag",
    "Item_Attach_Weapon_Magazine_QuickDraw_SniperRifle_C":
        "Sniper Rifle Quickdraw Mag",
    "Item_Attach_Weapon_Muzzle_Choke_C": "Choke",
    "Item_Attach_Weapon_Muzzle_Compensator_Large_C": "Large Compensator",
    "Item_Attach_Weapon_Muzzle_Compensator_Medium_C": "Medium Compensator",
    "Item_Attach_Weapon_Muzzle_Compensator_SniperRifle_C":
        "Sniper Rifle Compensator",
    "Item_Attach_Weapon_Muzzle_Duckbill_C": "Duckbill",
    "Item_Attach_Weapon_Muzzle_FlashHider_Large_C": "Large Flash Hider",
    "Item_Attach_Weapon_Muzzle_FlashHider_Medium_C": "Medium Flash Hider",
    "Item_Attach_Weapon_Muzzle_FlashHider_SniperRifle_C":
        "Sniper Rifle Flash Hider",
    "Item_Attach_Weapon_Muzzle_Suppressor_Large_C": "Large Supressor",
    "Item_Attach_Weapon_Muzzle_Suppressor_Medium_C": "Medium Supressor",
    "Item_Attach_Weapon_Muzzle_Suppressor_Small_C": "Small Supressor",
    "Item_Attach_Weapon_Muzzle_Suppressor_SniperRifle_C":
        "Sniper Rifle Supressor",
    "Item_Attach_Weapon_SideRail_DotSight_RMR_C": "Canted Sight",
    "Item_Attach_Weapon_Stock_AR_Composite_C": "Tactical Stock",
    "Item_Attach_Weapon_Stock_Shotgun_BulletLoops_C": "Shotgun Bullet Loops",
    "Item_Attach_Weapon_Stock_SniperRifle_BulletLoops_C":
        "Sniper Rifle Bullet Loops",
    "Item_Attach_Weapon_Stock_SniperRifle_CheekPad_C":
        "Sniper Rifle Cheek Pad",
    "Item_Attach_Weapon_Stock_UZI_C": "Uzi Stock",
    "Item_Attach_Weapon_Upper_ACOG_01_C": "4x ACOG Scope",
    "Item_Attach_Weapon_Upper_Aimpoint_C": "2x Aimpoint Scope",
    "Item_Attach_Weapon_Upper_CQBSS_C": "8x CQBSS Scope",
    "Item_Attach_Weapon_Upper_DotSight_01_C": "Red Dot Sight",
    "Item_Attach_Weapon_Upper_Holosight_C": "Holographic Sight",
    "Item_Attach_Weapon_Upper_PM2_01_C": "15x PM II Scope",
    "Item_Attach_Weapon_Upper_Scope3x_C": "3x Scope",
    "Item_Attach_Weapon_Upper_Scope6x_C": "6x Scope",
    "Item_Back_B_01_StartParachutePack_C": "Parachute",
    "Item_Back_C_01_Lv3_C": "Backpack (Level 3)",
    "Item_Back_C_02_Lv3_C": "Backpack (Level 3)",
    "Item_Back_E_01_Lv1_C": "Backpack (Level 1)",
    "Item_Back_E_02_Lv1_C": "Backpack (Level 1)",
    "Item_Back_F_01_Lv2_C": "Backpack (Level 2)",
    "Item_Back_F_02_Lv2_C": "Backpack (Level 2)",
    "Item_Boost_AdrenalineSyringe_C": "Adrenaline Syringe",
    "Item_Boost_EnergyDrink_C": "Energy Drink",
    "Item_Boost_PainKiller_C": "Painkiller",
    "Item_Ghillie_01_C": "Ghillie Suit",
    "Item_Ghillie_02_C": "Ghillie Suit",
    "Item_Ghillie_03_C": "Ghillie Suit",
    "Item_Ghillie_04_C": "Ghillie Suit",
    "Item_Head_E_01_Lv1_C": "Motorcycle Helmet (Level 1)",
    "Item_Head_E_02_Lv1_C": "Motorcycle Helmet (Level 1)",
    "Item_Head_F_01_Lv2_C": "Military Helmet (Level 2)",
    "Item_Head_F_02_Lv2_C": "Military Helmet (Level 2)",
    "Item_Head_G_01_Lv3_C": "Spetsnaz Helmet (Level 3)",
    "Item_Heal_Bandage_C": "Bandage",
    "Item_Heal_FirstAid_C": "First Aid Kit",
    "Item_Heal_MedKit_C": "Med kit",
    "Item_JerryCan_C": "Gas Can",
    "Item_Weapon_AK47_C": "AKM",
    "Item_Weapon_Apple_C": "Apple",
    "Item_Weapon_AUG_C": "AUG A3",
    "Item_Weapon_AWM_C": "AWM",
    "Item_Weapon_Berreta686_C": "S686",
    "Item_Weapon_BerylM762_C": "Beryl",
    "Item_Weapon_BizonPP19_C": "Bizon",
    "Item_Weapon_Cowbar_C": "Crowbar",
    "Item_Weapon_Crossbow_C": "Crossbow",
    "Item_Weapon_DesertEagle_C": "Deagle",
    "Item_Weapon_DP12_C": "DBS",
    "Item_Weapon_DP28_C": "DP-28",
    "Item_Weapon_FlareGun_C": "Flare Gun",
    "Item_Weapon_FlashBang_C": "Flashbang",
    "Item_Weapon_FNFal_C": "SLR",
    "Item_Weapon_G18_C": "P18C",
    "Item_Weapon_G36C_C": "G36C",
    "Item_Weapon_Grenade_C": "Frag Grenade",
    "Item_Weapon_Grenade_Warmode_C": "Frag Grenade",
    "Item_Weapon_Groza_C": "Groza",
    "Item_Weapon_HK416_C": "M416",
    "Item_Weapon_Kar98k_C": "Kar98k",
    "Item_Weapon_M16A4_C": "M16A4",
    "Item_Weapon_M1911_C": "P1911",
    "Item_Weapon_M249_C": "M249",
    "Item_Weapon_M24_C": "M24",
    "Item_Weapon_M9_C": "P92",
    "Item_Weapon_Machete_C": "Machete",
    "Item_Weapon_Mini14_C": "Mini 14",
    "Item_Weapon_Mk14_C": "Mk14 EBR",
    "Item_Weapon_Mk47Mutant_C": "Mk47 Mutant",
    "Item_Weapon_Molotov_C": "Molotov Cocktail",
    "Item_Weapon_MP5K_C": "MP5K",
    "Item_Weapon_NagantM1895_C": "R1895",
    "Item_Weapon_Pan_C": "Pan",
    "Item_Weapon_QBU88_C": "QBU88",
    "Item_Weapon_QBZ95_C": "QBZ95",
    "Item_Weapon_Rhino_C": "R45",
    "Item_Weapon_Saiga12_C": "S12K",
    "Item_Weapon_Sawnoff_C": "Sawed-off",
    "Item_Weapon_SCAR-L_C": "SCAR-L",
    "Item_Weapon_Sickle_C": "Sickle",
    "Item_Weapon_SKS_C": "SKS",
    "Item_Weapon_SmokeBomb_C": "Smoke Grenade",
    "Item_Weapon_Snowball_C": "Snowball",
    "Item_Weapon_Thompson_C": "Tommy Gun",
    "Item_Weapon_UMP_C": "UMP9",
    "Item_Weapon_UZI_C": "Micro Uzi",
    "Item_Weapon_Vector_C": "Vector",
    "Item_Weapon_VSS_C": "VSS",
    "Item_Weapon_vz61Skorpion_C": "Skorpion",
    "Item_Weapon_Win1894_C": "Win94",
    "Item_Weapon_Winchester_C": "S1897",
    "WarModeStartParachutePack_C": "Parachute"
}


VEHICLE_MAP = {
    "AquaRail_A_01_C": "Aquarail",
    "AquaRail_A_02_C": "Aquarail",
    "AquaRail_A_03_C": "Aquarail",
    "Boat_PG117_C": "PG-117",
    "BP_BRDM_C": "BRDM-2",
    "BP_M_Rony_A_01_C": "Rony",
    "BP_M_Rony_A_02_C": "Rony",
    "BP_M_Rony_A_03_C": "Rony",
    "BP_Mirado_A_02_C": "Mirado",
    "BP_Mirado_A_03_Esports_C": "Mirado",
    "BP_Mirado_Open_03_C": "Mirado (open top)",
    "BP_Mirado_Open_04_C": "Mirado (open top)",
    "BP_Motorbike_04_C": "Motorcycle",
    "BP_Motorbike_04_Desert_C": "Motorcycle",
    "BP_Motorbike_04_SideCar_C": "Motorcycle (w/ Sidecar)",
    "BP_Motorbike_04_SideCar_Desert_C": "Motorcycle (w/ Sidecar)",
    "BP_Niva_01_C": "Zima",
    "BP_Niva_02_C": "Zima",
    "BP_Niva_03_C": "Zima",
    "BP_Niva_04_C": "Zima",
    "BP_PickupTruck_A_01_C": "Pickup Truck (closed top)",
    "BP_PickupTruck_A_02_C": "Pickup Truck (closed top)",
    "BP_PickupTruck_A_03_C": "Pickup Truck (closed top)",
    "BP_PickupTruck_A_04_C": "Pickup Truck (closed top)",
    "BP_PickupTruck_A_05_C": "Pickup Truck (closed top)",
    "BP_PickupTruck_A_esports_C": "Pickup Truck (closed top)",
    "BP_PickupTruck_B_01_C": "Pickup Truck (open top)",
    "BP_PickupTruck_B_02_C": "Pickup Truck (open top)",
    "BP_PickupTruck_B_03_C": "Pickup Truck (open top)",
    "BP_PickupTruck_B_04_C": "Pickup Truck (open top)",
    "BP_PickupTruck_B_05_C": "Pickup Truck (open top)",
    "BP_TukTukTuk_A_01_C": "Tukshai",
    "BP_TukTukTuk_A_02_C": "Tukshai",
    "BP_TukTukTuk_A_03_C": "Tukshai",
    "BP_Van_A_01_C": "Van",
    "BP_Van_A_02_C": "Van",
    "BP_Van_A_03_C": "Van",
    "BP_Scooter_01_A_C": "Scooter",
    "BP_Scooter_02_A_C": "Scooter",
    "BP_Scooter_03_A_C": "Scooter",
    "BP_Scooter_04_A_C": "Scooter",
    "BP_Snowbike_01_C": "Snowbike",
    "BP_Snowbike_02_C": "Snowbike",
    "BP_Snowmobile_01_C": "Snowmobile",
    "BP_Snowmobile_02_C": "Snowmobile",
    "BP_Snowmobile_03_C": "Snowmobile",
    "Buggy_A_01_C": "Buggy",
    "Buggy_A_02_C": "Buggy",
    "Buggy_A_03_C": "Buggy",
    "Buggy_A_04_C": "Buggy",
    "Buggy_A_05_C": "Buggy",
    "Buggy_A_06_C": "Buggy",
    "Dacia_A_01_v2_C": "Dacia 1300",
    "Dacia_A_01_v2_snow_C": "Dacia 1300",
    "Dacia_A_02_v2_C": "Dacia 1300",
    "Dacia_A_03_v2_C": "Dacia 1300",
    "Dacia_A_03_v2_Esports_C": "Dacia 1300",
    "Dacia_A_04_v2_C": "Dacia 1300",
    "DummyTransportAircraft_C": "C-130",
    "ParachutePlayer_C": "Parachute",
    "ParachutePlayer_Warmode_C": "Parachute",
    "PG117_A_01_C": "PG-117",
    "Uaz_A_01_C": "UAZ (open top)",
    "Uaz_Armored_C": "UAZ (armored)",
    "Uaz_B_01_C": "UAZ (soft top)",
    "Uaz_B_01_esports_C": "UAZ (soft top)",
    "Uaz_C_01_C": "UAZ (hard top)",
    "WarModeTransportAircraft_C": "C-130"
}


DAMAGE_CAUSER_MAP = {
    "AquaRail_A_01_C": "Aquarail",
    "AquaRail_A_02_C": "Aquarail",
    "AquaRail_A_03_C": "Aquarail",
    "BattleRoyaleModeController_Def_C": "Bluezone",
    "BattleRoyaleModeController_Desert_C": "Bluezone",
    "BattleRoyaleModeController_DihorOtok_C": "Bluezone",
    "BattleRoyaleModeController_Savage_C": "Bluezone",
    "Boat_PG117_C": "PG-117",
    "BP_BRDM_C": "BRDM-2",
    "BP_M_Rony_A_01_C": "Rony",
    "BP_M_Rony_A_02_C": "Rony",
    "BP_M_Rony_A_03_C": "Rony",
    "BP_Mirado_A_02_C": "Mirado",
    "BP_Mirado_A_03_Esports_C": "Mirado",
    "BP_Mirado_Open_03_C": "Mirado (open top)",
    "BP_Mirado_Open_04_C": "Mirado (open top)",
    "BP_MolotovFireDebuff_C": "Molotov Fire Damage",
    "BP_Motorbike_04_C": "Motorcycle",
    "BP_Motorbike_04_Desert_C": "Motorcycle",
    "BP_Motorbike_04_SideCar_C": "Motorcycle (w/ Sidecar)",
    "BP_Motorbike_04_SideCar_Desert_C": "Motorcycle (w/ Sidecar)",
    "BP_Niva_01_C": "Zima",
    "BP_Niva_02_C": "Zima",
    "BP_Niva_03_C": "Zima",
    "BP_Niva_04_C": "Zima",
    "BP_PickupTruck_A_01_C": "Pickup Truck (closed top)",
    "BP_PickupTruck_A_02_C": "Pickup Truck (closed top)",
    "BP_PickupTruck_A_03_C": "Pickup Truck (closed top)",
    "BP_PickupTruck_A_04_C": "Pickup Truck (closed top)",
    "BP_PickupTruck_A_05_C": "Pickup Truck (closed top)",
    "BP_PickupTruck_A_esports_C": "Pickup Truck (closed top)",
    "BP_PickupTruck_B_01_C": "Pickup Truck (open top)",
    "BP_PickupTruck_B_02_C": "Pickup Truck (open top)",
    "BP_PickupTruck_B_03_C": "Pickup Truck (open top)",
    "BP_PickupTruck_B_04_C": "Pickup Truck (open top)",
    "BP_PickupTruck_B_05_C": "Pickup Truck (open top)",
    "BP_Scooter_01_A_C": "Scooter",
    "BP_Scooter_02_A_C": "Scooter",
    "BP_Scooter_03_A_C": "Scooter",
    "BP_Scooter_04_A_C": "Scooter",
    "BP_Snowbike_01_C": "Snowbike",
    "BP_Snowbike_02_C": "Snowbike",
    "BP_Snowmobile_01_C": "Snowmobile",
    "BP_Snowmobile_02_C": "Snowmobile",
    "BP_Snowmobile_03_C": "Snowmobile",
    "BP_TukTukTuk_A_01_C": "Tukshai",
    "BP_TukTukTuk_A_02_C": "Tukshai",
    "BP_TukTukTuk_A_03_C": "Tukshai",
    "BP_Van_A_01_C": "Van",
    "BP_Van_A_02_C": "Van",
    "BP_Van_A_03_C": "Van",
    "Buff_DecreaseBreathInApnea_C": "Drowning",
    "Buggy_A_01_C": "Buggy",
    "Buggy_A_02_C": "Buggy",
    "Buggy_A_03_C": "Buggy",
    "Buggy_A_04_C": "Buggy",
    "Buggy_A_05_C": "Buggy",
    "Buggy_A_06_C": "Buggy",
    "Dacia_A_01_v2_C": "Dacia",
    "Dacia_A_01_v2_snow_C": "Dacia",
    "Dacia_A_02_v2_C": "Dacia",
    "Dacia_A_03_v2_C": "Dacia",
    "Dacia_A_03_v2_Esports_C": "Dacia",
    "Dacia_A_04_v2_C": "Dacia",
    "Jerrycan": "Jerrycan",
    "None": "None",
    "PG117_A_01_C": "PG-117",
    "PlayerFemale_A_C": "Player",
    "PlayerMale_A_C": "Player",
    "ProjGrenade_C": "Frag Grenade",
    "ProjMolotov_C": "Molotov Cocktail",
    "ProjMolotov_DamageField_Direct_C": "Molotov Cocktail Fire Field",
    "RedZoneBomb_C": "Redzone",
    "Uaz_A_01_C": "UAZ (open top)",
    "Uaz_Armored_C": "UAZ (armored)",
    "Uaz_B_01_C": "UAZ (soft top)",
    "Uaz_B_01_esports_C": "UAZ (soft top)",
    "Uaz_C_01_C": "UAZ (hard top)",
    "WeapAK47_C": "AKM",
    "WeapAUG_C": "AUG A3",
    "WeapAWM_C": "AWM",
    "WeapBerreta686_C": "S686",
    "WeapBerylM762_C": "Beryl",
    "WeapBizonPP19_C": "Bizon",
    "WeapCowbar_C": "Crowbar",
    "WeapCrossbow_1_C": "Crossbow",
    "WeapDesertEagle_C": "Deagle",
    "WeapDP12_C": "DBS",
    "WeapDP28_C": "DP-28",
    "WeapFNFal_C": "SLR",
    "WeapG18_C": "P18C",
    "WeapG36C_C": "G36C",
    "WeapGroza_C": "Groza",
    "WeapHK416_C": "M416",
    "WeapKar98k_C": "Kar98k",
    "WeapM16A4_C": "M16A4",
    "WeapM1911_C": "P1911",
    "WeapM249_C": "M249",
    "WeapM24_C": "M24",
    "WeapM9_C": "P92",
    "WeapMachete_C": "Machete",
    "WeapMini14_C": "Mini 14",
    "WeapMk14_C": "Mk14 EBR",
    "WeapMk47Mutant_C": "Mk47 Mutant",
    "WeapMP5K_C": "MP5K",
    "WeapNagantM1895_C": "R1895",
    "WeapPan_C": "Pan",
    "WeapQBU88_C": "QBU88",
    "WeapQBZ95_C": "QBZ95",
    "WeapRhino_C": "R45",
    "WeapSaiga12_C": "S12K",
    "WeapSawnoff_C": "Sawed-off",
    "WeapSCAR-L_C": "SCAR-L",
    "WeapSickle_C": "Sickle",
    "WeapSKS_C": "SKS",
    "WeapThompson_C": "Tommy Gun",
    "WeapUMP_C": "UMP9",
    "WeapUZI_C": "Micro Uzi",
    "WeapVector_C": "Vector",
    "WeapVSS_C": "VSS",
    "Weapvz61Skorpion_C": "Skorpion",
    "WeapWin94_C": "Win94",
    "WeapWinchester_C": "S1897"
}


DAMAGE_TYPE_MAP = {
    "Damage_BlueZone": "Bluezone Damage",
    "Damage_Drown": "Drowning Damage",
    "Damage_Explosion_JerryCan": "Jerrycan Explosion Damage",
    "Damage_Explosion_Grenade": "Grenade Explosion Damage",
    "Damage_Explosion_RedZone": "Redzone Explosion Damage",
    "Damage_Explosion_Vehicle": "Vehicle Explosion Damage",
    "Damage_Groggy": "Bleed out damage",
    "Damage_Gun": "Gun Damage",
    "Damage_Instant_Fall": "Fall Damage",
    "Damage_Melee": "Melee Damage",
    "Damage_MeleeThrow": "Melee Throw Damage",
    "Damage_Molotov": "Molotov Damage",
    "Damage_Punch": "Punch Damage",
    "Damage_VehicleCrashHit": "Vehicle Crash Damage",
    "Damage_VehicleHit": "Vehicle Damage"
}

ATTACK_TYPE = [
    "RedZone",
    "Weapon"
]

DAMAGE_REASON = [
    "ArmShot",
    "HeadShot",
    "LegShot",
    "None",
    "NonSpecific",
    "PelvisShot",
    "TorsoShot"
]

MAP_NAME = {
    "Desert_Main": "Miramar",
    "DihorOtok_Main": "Vikendi",
    "Erangel_Main": "Erangel",
    "Baltic_Main": "Erangel (Remastered)",
    "Range_Main": "Camp Jackal",
    "Savage_Main": "Sanhok"
}

WEATHER_MAP = [
    "Clear",
    "Clear_02",
    "Dark",
    "Night",
    "Overcast",
    "Snow",
    "Sunrise",
    "Sunset",
    "Weather_Range_Sunset"
]

GAME_MODE = [
    "duo",
    "duo-fpp",
    "solo",
    "solo-fpp",
    "squad",
    "squad-fpp",
    "conquest-duo",
    "conquest-duo-fpp",
    "conquest-solo",
    "conquest-solo-fpp",
    "conquest-squad",
    "conquest-squad-fpp",
    "esports-duo",
    "esports-duo-fpp",
    "esports-solo",
    "esports-solo-fpp",
    "esports-squad",
    "esports-squad-fpp",
    "normal-duo",
    "normal-duo-fpp",
    "normal-solo",
    "normal-solo-fpp",
    "normal-squad",
    "normal-squad-fpp",
    "war-duo",
    "war-duo-fpp",
    "war-solo",
    "war-solo-fpp",
    "war-squad",
    "war-squad-fpp",
    "zombie-duo",
    "zombie-duo-fpp",
    "zombie-solo",
    "zombie-solo-fpp",
    "zombie-squad",
    "zombie-squad-fpp"
]

SEASON_STATE = [
    "closed",
    "prepare",
    "progress"
]

OBJECT_TYPE = [
    "Door",
    "Fence",
    "Jerrycan",
    "VendingMachine",
    "Window"
]

OBJECT_TYPE_STATUS = [
    'ACTIVATED',
    'Closing',
    'Opening'
]
